### ISSUE TITLE
horizontal scroll on Firefox-Mac

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/medicine.wsu.edu#159]
The site as a large amount of horizontal scroll on Firefox without any elements being noticeable to cause the issue.

Related to #158?

**Comment by jeremyfelt** [comment]
@slocker3 Is this on every page or a specific URL? I'm not able to reproduce in FF on Ubuntu.

**Comment by slocker3** [comment]
@jeremyfelt on three levels of pages that I have tested, including the homepage.

**Comment by slocker3** [comment]
@jeremyfelt I can't replicate the issue with other WSU sites, e.g., web.wsu.edu, wsu.edu

**Comment by slocker3** [comment]
Solved with #158 - see #158 for details.
