### ISSUE TITLE
.main-header should be populated with expected headings

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/medicine.wsu.edu#53]
The site header on all pages should have the following markup similar to the following:
```
<header class="main-header">
	<div class="hgroup">
		<div class="main-header-name">WSU College of Medicine Style Guide</div>
		<h1 class="main-header-description">Secondary page</h1>
	</div>
</header>
```
We need to ensure that `.main-header-name` and `.main-header-description` are populated as expected throughout the site.

In every page instance below there should be an ability to override the defaults with page-specific custom name and description

* [x] Home Page
    * Name: n/a
    * Description: n/a
* [x] Secondary Page
    * Name: none
    * Description: page title
* [x] Tertiary Page
    * Name: none
    * Description: parent page title
* [ ] Events Page
    * Name: none
    * Description: Events
* [ ] Single Event
    * Name: 
    * Description: Events
* [x] News Page
    * Name: 
    * Description: News
* [x] Single post
    * Name: 
    * Description: News
* [x] Category archive
    * Name: 
    * Description: Category: category-name
* [x] Tag archive
    * Name: 
    * Description: Tag: tag-name
* [x] Date Archive - Year
    * Name: 
    * Description: Archive: date
* [x] Date Archive - Month
    * Name: 
    * Description: Archive: Month
* [x] Date Archive - Day
    * Name: 
    * Description: Archive: day

**Comment by slocker3** [comment]
@jeremyfelt #review #thoughts?
